services:
  customers:
    image: customers-service:latest
    container_name: customers_service_container
    ports:
      - "8081:8080"
    networks:
      - bank_network

  transactions:
    image: transactions-service:latest
    container_name: transactions_service_container
    ports:
      - "8082:8080"
    networks:
      - bank_network

  accounts:
    image: accounts-service:latest
    container_name: accounts_service_container
    ports:
      - "8083:8080"
    networks:
      - bank_network

  financebff:
    image: financebff-service:latest
    container_name: financebff_service_container
    ports:
      - "8084:8080"
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge